<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 02 May 2018 19:24:28 +0800
 */

$conf['title'] = 'CH Wiki';
$conf['start'] = 'start';
$conf['breadcrumbs'] = 0;
$conf['basedir'] = '/';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin,@beheer';
// $conf['disableactions'] = 'register,check,subscribe,unsubscribe,resendpwd,profile';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;

$conf['authtype']    = 'authiapconnect2';
$conf['plugin']['authiapconnect2']['groups_endpoint']      = 'http://localhost:3001/groups/:email/slugs';
