<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 02 May 2018 19:24:28 +0800
 */

$conf['title'] = 'CH Wiki';
$conf['start'] = 'start';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin,@chbeheer';
$conf['disableactions'] = 'register,check,subscribe,unsubscribe,resendpwd,profile';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['authtype'] = 'oauth';

# OAuth2
$conf['plugin']['oauth']['singleService'] = 1;
$conf['plugin']['oauth']['register-on-auth'] = 1;
$conf['plugin']['oauth']['overwrite-groups'] = 1;

# OAuth2 Generic

$conf['plugin']['oauthgeneric']['key'] = getenv('WISVCH_CONNECT_CLIENT_ID');
$conf['plugin']['oauthgeneric']['secret'] = getenv('WISVCH_CONNECT_CLIENT_SECRET');
$conf['plugin']['oauthgeneric']['authurl'] = 'https://connect.ch.tudelft.nl/authorize';
$conf['plugin']['oauthgeneric']['tokenurl'] = 'https://connect.ch.tudelft.nl/token';
$conf['plugin']['oauthgeneric']['userurl'] = 'https://connect.ch.tudelft.nl/userinfo';
$conf['plugin']['oauthgeneric']['authmethod'] = '1';
$conf['plugin']['oauthgeneric']['scopes'] = array('openid', 'profile', 'email', 'ldap', 'openid');
$conf['plugin']['oauthgeneric']['json-user'] = 'sub';
$conf['plugin']['oauthgeneric']['json-name'] = 'name';
$conf['plugin']['oauthgeneric']['json-mail'] = 'email';
$conf['plugin']['oauthgeneric']['json-grps'] = 'ldap_groups';
